### ISSUE TITLE
Users allowed to rename courses update seems to be not working

### ISSUE THREAD

**Issue by PanSwift** [perslev/CanvasSync#13]
line 174 and 176 in the file ("~\Anaconda3\Lib\site-packages\CanvasSync\Settings\user_prompter.py") seems to be not working on python 3.6, it appears to have the same problem later on.

for line 174, suggest to amend as follow.
courses = [course[u'name']for course in courses for name in course if name ==u'name']

**Comment by perslev** [comment]
The ability to rename courses has been removed in the latest version (v0.2.4) as it was poorly supported.

If this is a feature of interest, please let me know as it may be added in a later version.
