### ISSUE TITLE
Remove invalid characters from file and folder names

### ISSUE THREAD

**Issue by vanalmsick** [perslev/CanvasSync#15]
First of all: CanvasSync IS REALLY GREAT!!! I love it!

I set up CanvasSync on a folder that syncs with my OneDrive Cloud. 
But OneDrive does not allow folder and file names that begin or end with a space, begin with two full stops, end with one full stop, or contain any of these characters: \ / : * ? " < > |

However, some profs made folders ending with a space. Therefore, could you please add a type of file-/folder-name-filter that automatically replaces not allowed characters?

**Comment by perslev** [comment]
Hi, thank you for your feedback!

This issue should be resolved in the newest update (v0.2.4). Previously, those characters would only be replaced on Window systems, but now this is done for all users.

Feel free to open another issue if this is still causing problems.

**Comment by vanalmsick** [comment]
Hey, thanks now it works fine with files and folders on my Mac!

The files and folders now work fine but if you have an assignment that has a long title this title is shortened with '..' at the end (Not sure why it is shortened to 62 characters - usually 250 is the limit). 
_(Example: Assignment name "Master of Finance Intake 2019 - Recognition Guidelines for Prior Academic Achievements" -> "Master of Finance Intake 2019 - Recognition Guidelines for P..")_ 

This shortening causes again a OneDrive sync error cause "." is not allowed to be the last character of a folder (or file).
Hope that helps finding the cause. If you need some more info just give me a short note.

**Comment by perslev** [comment]
Good catch, thanks! File- and foldernames are now only shortened to a max of 255 characters and '..' are no longer added to the end of shortened names.
